### ISSUE TITLE
Project should work correctly without areas definition when integrates with NelmioApiDocBundle

### ISSUE THREAD

**Issue by adrenalinkin** [adrenalinkin/swagger-resolver-bundle#69]
Caused by #64 

Presents we should define `area` explicitly:
```
nelmio_api_doc:
    areas:
        default:
            host_patterns:
                - '^api\.'
```
